name: Build and install ansible collection
description: Build and install ansible collection

inputs:
  collection_namespace:
    description: "Install collection python dependencies"
    required: true
  collection_name:
    description: "Path to the collection source"
    required: true
  collection_version:
    description: The final collection path
    required: false
outputs:
  tar_file:
    description: The collection tarball when built
    value: ${{ collection_namespace }}-${{ collection_name }}-${{ collection_version }}.tar.gz
  collection_path:
    description: The final collection path
    value: /home/runner/collections/ansible_collections/${{ collection_namespace }}/${{ collection_name }}

runs:
  using: composite
  steps:
    - name: template galaxy file
      run: ansible all -i local -m template -a "src=galaxy.yml.j2 dest=galaxy.yml"
      shell: bash

    - name: Build collection
      run: ansible-galaxy collection build -vvv
      shell: bash
      working-directory: ${{ inputs.source_path }}

    - name: Install collection
      run: ansible-galaxy collection install ./${{ collection_namespace }}-${{ collection_name }}-${{ collection_version }}.tar.gz -p /home/runner/collections
      shell: bash
      working-directory: ${{ inputs.source_path }}